// Kertas Ujian UASA Percubaan #3 — Matematik Tingkatan 3. Format sama seperti
// Set 1 dan Set 2 (Bahagian A/B/C, 100 markah, 31 soalan, 120 minit),
// merentasi SEMUA 9 bab, dengan nombor dan konteks BERBEZA lagi.
export const form3UasaPaper3 = {
  id: "form3-uasa-3",
  formId: "form3",
  examTypeLabel: "UASA",
  title: "Ujian UASA Percubaan (Set 3)",
  subtitle: "Matematik · Tingkatan 3",
  totalMarks: 100,
  durationMinutes: 120,
  sections: [
    {
      key: "A",
      label: "Bahagian A",
      instruction: "Jawab SEMUA soalan. Setiap soalan bernilai 1 markah.",
      type: "mcq",
      questions: [
        { id: "A1", topic: "Bab 1 · Indeks", marks: 1, prompt: "Nilaikan 5³.", choices: ["125", "15", "53", "25"], answer: "125" },
        { id: "A2", topic: "Bab 1 · Indeks", marks: 1, prompt: "Permudahkan (2³)² dalam bentuk indeks.", choices: ["2⁶", "2⁵", "2⁹", "2¹"], answer: "2⁶" },
        { id: "A3", topic: "Bab 2 · Bentuk Piawai", marks: 1, prompt: "Berapakah bilangan angka bererti dalam 0.00206?", choices: ["3", "2", "6", "5"], answer: "3" },
        { id: "A4", topic: "Bab 2 · Bentuk Piawai", marks: 1, prompt: "Tulis 910000 dalam bentuk piawai.", choices: ["9.1 × 10⁵", "9.1 × 10⁴", "91 × 10⁴", "9.1 × 10⁶"], answer: "9.1 × 10⁵" },
        { id: "A5", topic: "Bab 3 · Matematik Pengguna", marks: 1, prompt: "Kirakan faedah mudah bagi P=RM6000, r=3% setahun, t=4 tahun.", choices: ["RM720", "RM180", "RM6720", "RM360"], answer: "RM720" },
        { id: "A6", topic: "Bab 3 · Matematik Pengguna", marks: 1, prompt: "Pinjaman RM4000 pada faedah sama rata 5% setahun selama 3 tahun. Cari jumlah bayaran balik A.", choices: ["RM4600", "RM600", "RM4000", "RM4500"], answer: "RM4600" },
        { id: "A7", topic: "Bab 4 · Lukisan Berskala", marks: 1, prompt: "Skala 1:40. Ukuran lukisan 5 cm. Apakah ukuran sebenar?", choices: ["200 cm", "45 cm", "35 cm", "8 cm"], answer: "200 cm" },
        { id: "A8", topic: "Bab 4 · Lukisan Berskala", marks: 1, prompt: "Ukuran sebenar 600 cm dilukis sebagai 4 cm. Apakah skala?", choices: ["1:150", "150:1", "1:4", "1:600"], answer: "1:150" },
        { id: "A9", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Segi tiga bersudut tegak: bertentangan θ = 5, hipotenus = 13. Cari sin θ (2 tempat perpuluhan).", choices: ["0.38", "0.92", "2.6", "0.62"], answer: "0.38" },
        { id: "A10", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Apakah nilai sin 45° (2 tempat perpuluhan)?", choices: ["0.71", "1", "0.5", "1.41"], answer: "0.71" },
        { id: "A11", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Apakah nilai kos 30° (2 tempat perpuluhan)?", choices: ["0.87", "0.5", "1", "1.73"], answer: "0.87" },
        { id: "A12", topic: "Bab 6 · Sudut dan Tangen bagi Bulatan", marks: 1, prompt: "Sudut lilitan dicangkum lengkok AB ialah 63°. Cari sudut pusat dicangkum lengkok yang sama.", choices: ["126°", "31.5°", "189°", "63°"], answer: "126°" },
        { id: "A13", topic: "Bab 6 · Sudut dan Tangen bagi Bulatan", marks: 1, prompt: "XZ ialah diameter bulatan, Y pada lilitan. Apakah sudut XYZ?", choices: ["90°", "45°", "180°", "60°"], answer: "90°" },
        { id: "A14", topic: "Bab 6 · Sudut dan Tangen bagi Bulatan", marks: 1, prompt: "ABCD sisi empat kitaran, ∠B = 95°. Cari ∠D (bertentangan).", choices: ["85°", "95°", "180°", "47.5°"], answer: "85°" },
        { id: "A15", topic: "Bab 7 · Pelan dan Dongakan", marks: 1, prompt: "Kuboid 7 cm × 3 cm × 2 cm. Cari luas unjuran dari SISI (lebar × tinggi).", choices: ["6 cm²", "21 cm²", "14 cm²", "42 cm²"], answer: "6 cm²" },
        { id: "A16", topic: "Bab 7 · Pelan dan Dongakan", marks: 1, prompt: "Garis padu TEBAL digunakan untuk sisi yang bagaimana?", choices: ["Nampak", "Terlindung", "Binaan", "Tiada kaitan"], answer: "Nampak" },
        { id: "A17", topic: "Bab 8 · Lokus dalam Dua Dimensi", marks: 1, prompt: "Apakah bentuk lokus titik SAMA JARAK daripada dua garis lurus SELARI?", choices: ["Satu garis selari di tengah-tengah", "Dua garis selari", "Bulatan", "Pembahagi sudut"], answer: "Satu garis selari di tengah-tengah" },
        { id: "A18", topic: "Bab 8 · Lokus dalam Dua Dimensi", marks: 1, prompt: "Lokus 'jarak KURANG daripada 5 cm daripada titik P' membentuk apa?", choices: ["Kawasan di dalam bulatan jejari 5 cm", "Bulatan sahaja (garis lilitan)", "Kawasan di luar bulatan", "Satu titik"], answer: "Kawasan di dalam bulatan jejari 5 cm" },
        { id: "A19", topic: "Bab 9 · Garis Lurus", marks: 1, prompt: "Garis 4x + 2y = 10 ditukar kepada bentuk y = mx + c. Apakah nilai m?", choices: ["-2", "2", "5", "-5"], answer: "-2" },
        { id: "A20", topic: "Bab 9 · Garis Lurus", marks: 1, prompt: "Adakah titik (3, −1) terletak pada garis y = 3x − 10?", choices: ["Ya, sebab 3(3)−10 = −1", "Tidak", "Tidak dapat ditentukan", "Ya tapi hanya untuk x positif"], answer: "Ya, sebab 3(3)−10 = −1" },
      ],
    },
    {
      key: "B",
      label: "Bahagian B",
      instruction: "Jawab SEMUA soalan. Tunjukkan kerja mengira kamu sebelum taip jawapan akhir setiap bahagian.",
      type: "structured",
      questions: [
        {
          id: "B1",
          topic: "Bab 1 · Indeks",
          isKbat: false,
          context: "Diberi ungkapan 6² × 6³, dipermudahkan kepada bentuk indeks 6ⁿ.",
          parts: [
            { label: "(a)", prompt: "Apakah nilai n?", answer: "5", marks: 2 },
            { label: "(b)", prompt: "Nilaikan 6ⁿ.", answer: "7776", marks: 2 },
          ],
          solution: ["6² × 6³ = 6²⁺³ = 6⁵, jadi n = 5", "6⁵ = 7776"],
        },
        {
          id: "B2",
          topic: "Bab 2 · Bentuk Piawai",
          isKbat: false,
          context: "Sebuah syarikat mencatat untung RM87000, ditulis dalam bentuk piawai A × 10ⁿ.",
          parts: [
            { label: "(a)", prompt: "Apakah nilai A?", answer: "8.7", marks: 2 },
            { label: "(b)", prompt: "Apakah nilai n?", answer: "4", marks: 2 },
          ],
          solution: ["87000 = 8.7 × 10⁴ (titik perpuluhan digerakkan 4 tempat ke kiri)", "Jadi A = 8.7 dan n = 4"],
        },
        {
          id: "B3",
          topic: "Bab 3 · Matematik Pengguna",
          isKbat: false,
          context: "Faizal melabur RM2800 pada faedah mudah 5% setahun selama 3 tahun.",
          parts: [
            { label: "(a)", prompt: "Cari faedah (RM).", answer: "420", marks: 2 },
            { label: "(b)", prompt: "Cari jumlah akhir dalam akaunnya (RM).", answer: "3220", marks: 2 },
          ],
          solution: ["I = Prt = 2800 × 0.05 × 3 = RM420", "Jumlah akhir = 2800 + 420 = RM3220"],
        },
        {
          id: "B4",
          topic: "Bab 4 · Lukisan Berskala",
          isKbat: false,
          context: "Skala sebuah lukisan ialah 1:12000. Jarak pada lukisan ialah 7 cm.",
          parts: [
            { label: "(a)", prompt: "Cari jarak sebenar (cm).", answer: "84000", marks: 2 },
            { label: "(b)", prompt: "Tukar jarak sebenar itu kepada m.", answer: "840", marks: 2 },
          ],
          solution: ["Jarak sebenar = 7 × 12000 = 84000 cm", "84000 cm = 840 m"],
        },
        {
          id: "B5",
          topic: "Bab 5 · Nisbah Trigonometri",
          isKbat: false,
          context: "Segi tiga bersudut tegak mempunyai sisi bertentangan θ = 10, sisi bersebelahan = 24, hipotenus = 26.",
          parts: [
            { label: "(a)", prompt: "Cari sin θ (2 tempat perpuluhan).", answer: "0.38", marks: 2 },
            { label: "(b)", prompt: "Cari kos θ (2 tempat perpuluhan).", answer: "0.92", marks: 2 },
          ],
          solution: ["sin θ = 10 ÷ 26 = 0.3846, dibundarkan = 0.38", "kos θ = 24 ÷ 26 = 0.9231, dibundarkan = 0.92"],
        },
      ],
    },
    {
      key: "C",
      label: "Bahagian C",
      instruction:
        "Jawab SEMUA soalan. Bahagian ini soalan KBAT (Kemahiran Berfikir Aras Tinggi) — perlukan penaakulan berbilang langkah, bukan sekadar satu formula.",
      type: "structured",
      questions: [
        {
          id: "C1",
          topic: "Bab 6 · Sudut dan Tangen bagi Bulatan (KBAT)",
          isKbat: true,
          context: "Bulatan berpusat O berjejari 9 cm. Titik luar T mempunyai tangen TA = 12 cm (A titik sentuhan).",
          parts: [
            { label: "(a)", prompt: "Cari OT (cm).", answer: "15", marks: 4 },
            { label: "(b)", prompt: "Perentas AB dilukis daripada A, dengan sudut TAB = 38°. Guna teorem sudut tembereng selang-seli, cari sudut ACB.", answer: "38", marks: 3 },
            { label: "(c)", prompt: "Jika ABCD ialah sisi empat kitaran dengan ∠C = ∠ACB = 38°, cari ∠A.", answer: "142", marks: 3 },
          ],
          solution: [
            "OA ⊥ TA, jadi OT² = OA² + TA² = 9² + 12² = 81 + 144 = 225, OT = 15 cm",
            "Teorem sudut tembereng selang-seli: sudut ACB = sudut TAB = 38°",
            "Sudut bertentangan sisi empat kitaran = 180°: ∠A = 180 − 38 = 142°",
          ],
        },
        {
          id: "C2",
          topic: "Bab 7 · Pelan dan Dongakan (KBAT)",
          isKbat: true,
          context: "Sebuah rumah berbentuk kuboid bertapak 10 m × 6 m, dinding setinggi 4 m, dengan bumbung piramid setinggi 2.5 m di atasnya.",
          parts: [
            { label: "(a)", prompt: "Cari luas pelan (tapak) rumah itu (m²).", answer: "60", marks: 4 },
            { label: "(b)", prompt: "Cari tinggi keseluruhan dongakan hadapan (dinding + bumbung, m).", answer: "6.5", marks: 3 },
            { label: "(c)", prompt: "Jika rumah dilukis pada skala 1:100, cari panjang (cm) sisi 10 m pada lukisan pelan.", answer: "10", marks: 3 },
          ],
          solution: [
            "Luas pelan = 10 × 6 = 60 m²",
            "Tinggi keseluruhan = 4 + 2.5 = 6.5 m",
            "10 m = 1000 cm, pada skala 1:100: 1000 ÷ 100 = 10 cm",
          ],
        },
        {
          id: "C3",
          topic: "Bab 8 · Lokus dalam Dua Dimensi (KBAT)",
          isKbat: true,
          context: "Seekor kuda diikat dengan tali sepanjang 13 m pada sebatang pancang. (Gunakan π ≈ 3.14)",
          parts: [
            { label: "(a)", prompt: "Nyatakan bentuk lokus kawasan yang boleh diragut kuda itu (satu perkataan).", answer: "Bulatan", marks: 3 },
            { label: "(b)", prompt: "Cari luas kawasan meragut itu (bundarkan kepada nombor bulat, m²).", answer: "531", marks: 4 },
            { label: "(c)", prompt: "Jika tali diperpanjang kepada 15 m, cari luas kawasan meragut baharu (bundarkan kepada nombor bulat, m²).", answer: "707", marks: 3 },
          ],
          solution: [
            "Jarak tetap daripada satu titik (pancang) — lokus ialah BULATAN",
            "Luas = πr² = 3.14 × 13 × 13 = 530.66, dibundarkan = 531 m²",
            "Luas baharu = 3.14 × 15 × 15 = 706.5, dibundarkan = 707 m²",
          ],
        },
        {
          id: "C4",
          topic: "Bab 9 · Garis Lurus (KBAT)",
          isKbat: true,
          context: "Garis L1: y = 3x − 2. Garis L2 SELARI dengan L1 dan melalui titik (5, 7).",
          parts: [
            { label: "(a)", prompt: "Cari kecerunan L1.", answer: "3", marks: 3 },
            { label: "(b)", prompt: "Cari nilai c (pintasan-y) bagi L2.", answer: "-8", marks: 4 },
            { label: "(c)", prompt: "Guna persamaan L2, cari nilai-y apabila x = 10.", answer: "22", marks: 3 },
          ],
          solution: [
            "Kecerunan L1 = 3",
            "L2 selari, jadi kecerunan L2 = 3. y = 3x + c melalui (5,7): 7 = 3(5) + c → c = −8",
            "L2: y = 3x − 8. Apabila x = 10: y = 3(10) − 8 = 22",
          ],
        },
        {
          id: "C5",
          topic: "Bab 1 dan 3 · Indeks & Matematik Pengguna (KBAT)",
          isKbat: true,
          context: "Sebuah pelaburan bermula RM600 dan berganda mengikut faktor 2 setiap 4 tahun (nilai = 600 × 2ⁿ, dengan n = bilangan kitaran 4 tahun).",
          parts: [
            { label: "(a)", prompt: "Cari nilai pelaburan (RM) selepas 12 tahun (n = 3).", answer: "4800", marks: 4 },
            { label: "(b)", prompt: "Selepas berapa TAHUN nilai pelaburan mencapai RM9600?", answer: "16", marks: 3 },
            { label: "(c)", prompt: "Selepas 20 tahun, faktor pendaraban ialah 2ᵏ. Apakah nilai k?", answer: "5", marks: 3 },
          ],
          solution: [
            "Selepas 12 tahun, n = 12 ÷ 4 = 3: nilai = 600 × 2³ = 600 × 8 = RM4800",
            "RM9600 = 600 × 2ⁿ → 2ⁿ = 16 = 2⁴ → n = 4 → tahun = 4 × 4 = 16 tahun",
            "Selepas 20 tahun, n = 20 ÷ 4 = 5, jadi k = 5",
          ],
        },
        {
          id: "C6",
          topic: "Bab 2 dan 4 · Bentuk Piawai & Lukisan Berskala (KBAT)",
          isKbat: true,
          context: "Jarak sebenar antara dua bandar ialah 3.6 × 10⁴ m. Sebuah peta menggunakan skala 1:60000.",
          parts: [
            { label: "(a)", prompt: "Tukar jarak sebenar itu kepada nombor biasa (m).", answer: "36000", marks: 3 },
            { label: "(b)", prompt: "Cari jarak pada peta (cm).", answer: "60", marks: 4 },
            { label: "(c)", prompt: "36000 ditulis sebagai 3.6 × 10ⁿ. Apakah nilai n?", answer: "4", marks: 3 },
          ],
          solution: [
            "3.6 × 10⁴ = 36000 m",
            "36000 m = 3600000 cm. Jarak pada peta = 3600000 ÷ 60000 = 60 cm",
            "36000 = 3.6 × 10⁴, jadi n = 4",
          ],
        },
      ],
    },
  ],
};
