// Kertas Ujian UPSA Percubaan #2 — Matematik Tingkatan 3. Format sama seperti
// Set 1 (Bahagian A/B/C, 100 markah, 31 soalan, 90 minit, Bab 1–5 sahaja),
// dengan nombor dan konteks BERBEZA.
export const form3UpsaPaper2 = {
  id: "form3-upsa-2",
  formId: "form3",
  examTypeLabel: "UPSA",
  title: "Ujian UPSA Percubaan (Set 2)",
  subtitle: "Matematik · Tingkatan 3 (Pertengahan Tahun · Bab 1–5)",
  totalMarks: 100,
  durationMinutes: 90,
  sections: [
    {
      key: "A",
      label: "Bahagian A",
      instruction: "Jawab SEMUA soalan. Setiap soalan bernilai 1 markah.",
      type: "mcq",
      questions: [
        { id: "A1", topic: "Bab 1 · Indeks", marks: 1, prompt: "Nilaikan 6².", choices: ["36", "12", "62", "26"], answer: "36" },
        { id: "A2", topic: "Bab 1 · Indeks", marks: 1, prompt: "Permudahkan 3⁴ × 3² dalam bentuk indeks.", choices: ["3⁶", "3⁸", "3²", "9⁶"], answer: "3⁶" },
        { id: "A3", topic: "Bab 1 · Indeks", marks: 1, prompt: "Nilaikan 8⁰.", choices: ["1", "0", "8", "80"], answer: "1" },
        { id: "A4", topic: "Bab 1 · Indeks", marks: 1, prompt: "Nilaikan 3⁻¹ dalam bentuk pecahan.", choices: ["1/3", "-3", "3", "-1/3"], answer: "1/3" },
        { id: "A5", topic: "Bab 2 · Bentuk Piawai", marks: 1, prompt: "Berapakah bilangan angka bererti dalam 6004?", choices: ["4", "2", "3", "1"], answer: "4" },
        { id: "A6", topic: "Bab 2 · Bentuk Piawai", marks: 1, prompt: "Berapakah bilangan angka bererti dalam 0.0500?", choices: ["3", "2", "4", "1"], answer: "3" },
        { id: "A7", topic: "Bab 2 · Bentuk Piawai", marks: 1, prompt: "Tulis 470000 dalam bentuk piawai.", choices: ["4.7 × 10⁵", "4.7 × 10⁴", "47 × 10⁴", "4.7 × 10⁶"], answer: "4.7 × 10⁵" },
        { id: "A8", topic: "Bab 2 · Bentuk Piawai", marks: 1, prompt: "Tulis 0.0032 dalam bentuk piawai.", choices: ["3.2 × 10⁻³", "3.2 × 10³", "32 × 10⁻⁴", "3.2 × 10⁻²"], answer: "3.2 × 10⁻³" },
        { id: "A9", topic: "Bab 3 · Matematik Pengguna", marks: 1, prompt: "Kirakan faedah mudah bagi P=RM1500, r=4% setahun, t=5 tahun.", choices: ["RM300", "RM75", "RM1800", "RM150"], answer: "RM300" },
        { id: "A10", topic: "Bab 3 · Matematik Pengguna", marks: 1, prompt: "Pinjaman RM2000 pada faedah sama rata 10% setahun selama 1 tahun. Cari jumlah bayaran balik A.", choices: ["RM2200", "RM200", "RM2000", "RM2100"], answer: "RM2200" },
        { id: "A11", topic: "Bab 3 · Matematik Pengguna", marks: 1, prompt: "Apakah maksud \"hutang\" (debt)?", choices: ["Jumlah wang yang masih perlu dibayar balik", "Jumlah wang simpanan", "Jumlah faedah sahaja", "Jumlah pelaburan sahaja"], answer: "Jumlah wang yang masih perlu dibayar balik" },
        { id: "A12", topic: "Bab 3 · Matematik Pengguna", marks: 1, prompt: "Apakah kesan BAYAR LEWAT bagi penggunaan kad kredit?", choices: ["Caj kewangan tambahan dikenakan", "Tiada kesan", "Kad terus dibatalkan", "Faedah dihapuskan"], answer: "Caj kewangan tambahan dikenakan" },
        { id: "A13", topic: "Bab 4 · Lukisan Berskala", marks: 1, prompt: "Skala 1:60. Ukuran lukisan 3 cm. Apakah ukuran sebenar?", choices: ["180 cm", "63 cm", "57 cm", "20 cm"], answer: "180 cm" },
        { id: "A14", topic: "Bab 4 · Lukisan Berskala", marks: 1, prompt: "Ukuran sebenar 240 cm dilukis sebagai 6 cm. Apakah skala?", choices: ["1:40", "40:1", "1:6", "1:240"], answer: "1:40" },
        { id: "A15", topic: "Bab 4 · Lukisan Berskala", marks: 1, prompt: "Skala 1:150. Ukuran sebenar 900 cm. Apakah ukuran lukisan?", choices: ["6 cm", "135000 cm", "150 cm", "144 cm"], answer: "6 cm" },
        { id: "A16", topic: "Bab 4 · Lukisan Berskala", marks: 1, prompt: "Apakah yang DIKEKALKAN antara lukisan berskala dengan objek sebenar?", choices: ["Bentuk (nisbah sama pada semua bahagian)", "Warna", "Bahan", "Berat"], answer: "Bentuk (nisbah sama pada semua bahagian)" },
        { id: "A17", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Segi tiga bersudut tegak: bertentangan θ = 12, hipotenus = 13. Cari sin θ (2 tempat perpuluhan).", choices: ["0.92", "0.38", "2.6", "0.62"], answer: "0.92" },
        { id: "A18", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Apakah nilai sin 60° (2 tempat perpuluhan)?", choices: ["0.87", "0.5", "1", "1.73"], answer: "0.87" },
        { id: "A19", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Segi tiga bersudut tegak: bersebelahan θ = 5, hipotenus = 13. Cari kos θ (2 tempat perpuluhan).", choices: ["0.38", "0.92", "2.6", "0.62"], answer: "0.38" },
        { id: "A20", topic: "Bab 5 · Nisbah Trigonometri", marks: 1, prompt: "Apabila sudut θ membesar daripada 0° ke 90°, apa berlaku kepada nilai tan θ?", choices: ["Bertambah", "Berkurang", "Kekal sama", "Menjadi negatif"], answer: "Bertambah" },
      ],
    },
    {
      key: "B",
      label: "Bahagian B",
      instruction: "Jawab SEMUA soalan. Tunjukkan kerja mengira kamu sebelum taip jawapan akhir setiap bahagian.",
      type: "structured",
      questions: [
        {
          id: "B1",
          topic: "Bab 1 · Indeks",
          isKbat: false,
          context: "Diberi ungkapan 5³ × 5², dipermudahkan kepada bentuk indeks 5ⁿ.",
          parts: [
            { label: "(a)", prompt: "Apakah nilai n?", answer: "5", marks: 2 },
            { label: "(b)", prompt: "Nilaikan 5ⁿ.", answer: "3125", marks: 2 },
          ],
          solution: ["5³ × 5² = 5³⁺² = 5⁵, jadi n = 5", "5⁵ = 3125"],
        },
        {
          id: "B2",
          topic: "Bab 2 · Bentuk Piawai",
          isKbat: false,
          context: "Sebuah stadium memuatkan 92000 penonton, ditulis dalam bentuk piawai A × 10ⁿ.",
          parts: [
            { label: "(a)", prompt: "Apakah nilai A?", answer: "9.2", marks: 2 },
            { label: "(b)", prompt: "Apakah nilai n?", answer: "4", marks: 2 },
          ],
          solution: ["92000 = 9.2 × 10⁴", "Jadi A = 9.2 dan n = 4"],
        },
        {
          id: "B3",
          topic: "Bab 3 · Matematik Pengguna",
          isKbat: false,
          context: "Zul melabur RM2200 pada faedah mudah 5% setahun selama 3 tahun.",
          parts: [
            { label: "(a)", prompt: "Cari faedah (RM).", answer: "330", marks: 2 },
            { label: "(b)", prompt: "Cari jumlah akhir dalam akaunnya (RM).", answer: "2530", marks: 2 },
          ],
          solution: ["I = Prt = 2200 × 0.05 × 3 = RM330", "Jumlah akhir = 2200 + 330 = RM2530"],
        },
        {
          id: "B4",
          topic: "Bab 4 · Lukisan Berskala",
          isKbat: false,
          context: "Skala sebuah lukisan ialah 1:9000. Jarak pada lukisan ialah 4 cm.",
          parts: [
            { label: "(a)", prompt: "Cari jarak sebenar (cm).", answer: "36000", marks: 2 },
            { label: "(b)", prompt: "Tukar jarak sebenar itu kepada m.", answer: "360", marks: 2 },
          ],
          solution: ["Jarak sebenar = 4 × 9000 = 36000 cm", "36000 cm = 360 m"],
        },
        {
          id: "B5",
          topic: "Bab 5 · Nisbah Trigonometri",
          isKbat: false,
          context: "Segi tiga bersudut tegak mempunyai sisi bertentangan θ = 20, sisi bersebelahan = 21, hipotenus = 29.",
          parts: [
            { label: "(a)", prompt: "Cari sin θ (2 tempat perpuluhan).", answer: "0.69", marks: 2 },
            { label: "(b)", prompt: "Cari kos θ (2 tempat perpuluhan).", answer: "0.72", marks: 2 },
          ],
          solution: ["sin θ = 20 ÷ 29 = 0.6897, dibundarkan = 0.69", "kos θ = 21 ÷ 29 = 0.7241, dibundarkan = 0.72"],
        },
      ],
    },
    {
      key: "C",
      label: "Bahagian C",
      instruction:
        "Jawab SEMUA soalan. Bahagian ini soalan KBAT (Kemahiran Berfikir Aras Tinggi) — perlukan penaakulan berbilang langkah, bukan sekadar satu formula.",
      type: "structured",
      questions: [
        {
          id: "C1",
          topic: "Bab 1 · Indeks (KBAT)",
          isKbat: true,
          context: "Nilai sebuah kereta menyusut mengikut faktor ½ setiap 2 tahun, bermula RM64000 (nilai = 64000 × (½)ⁿ, dengan n = bilangan kitaran 2 tahun).",
          parts: [
            { label: "(a)", prompt: "Cari nilai kereta (RM) selepas 4 tahun (n = 2).", answer: "16000", marks: 4 },
            { label: "(b)", prompt: "Selepas berapa TAHUN nilai kereta menjadi RM8000?", answer: "6", marks: 3 },
            { label: "(c)", prompt: "Cari nilai kereta (RM) selepas 8 tahun.", answer: "4000", marks: 3 },
          ],
          solution: [
            "Selepas 4 tahun, n = 2: nilai = 64000 × (½)² = 64000 ÷ 4 = RM16000",
            "(½)ⁿ = 8000 ÷ 64000 = ⅛ = (½)³ → n = 3 → tahun = 3 × 2 = 6 tahun",
            "Selepas 8 tahun, n = 4: nilai = 64000 × (½)⁴ = 64000 ÷ 16 = RM4000",
          ],
        },
        {
          id: "C2",
          topic: "Bab 2 · Bentuk Piawai (KBAT)",
          isKbat: true,
          context: "Jarak Bumi–Marikh lebih kurang 7.8 × 10⁷ km. Jarak Bumi–Bulan lebih kurang 3.9 × 10⁵ km.",
          parts: [
            { label: "(a)", prompt: "Berapa kali ganda jarak Bumi–Marikh berbanding jarak Bumi–Bulan?", answer: "200", marks: 4 },
            { label: "(b)", prompt: "Tulis 3.9 × 10⁵ sebagai nombor biasa (km).", answer: "390000", marks: 3 },
            { label: "(c)", prompt: "Berapakah bilangan angka bererti dalam 3.9 (bahagian A)?", answer: "2", marks: 3 },
          ],
          solution: [
            "(7.8 × 10⁷) ÷ (3.9 × 10⁵) = 2 × 10² = 200 kali ganda",
            "3.9 × 10⁵ = 390000 km",
            "3.9 ada 2 angka bererti (3 dan 9)",
          ],
        },
        {
          id: "C3",
          topic: "Bab 3 · Matematik Pengguna (KBAT)",
          isKbat: true,
          context: "Sebuah restoran meminjam RM15000 pada faedah sama rata 4% setahun selama 5 tahun, dibayar balik secara ansuran bulanan sama.",
          parts: [
            { label: "(a)", prompt: "Cari jumlah faedah (RM).", answer: "3000", marks: 3 },
            { label: "(b)", prompt: "Cari jumlah bayaran balik keseluruhan A (RM).", answer: "18000", marks: 3 },
            { label: "(c)", prompt: "Cari ansuran bulanan (RM).", answer: "300", marks: 4 },
          ],
          solution: [
            "Faedah = 15000 × 0.04 × 5 = RM3000",
            "A = 15000 + 3000 = RM18000",
            "Tempoh 5 tahun = 60 bulan. Ansuran bulanan = 18000 ÷ 60 = RM300",
          ],
        },
        {
          id: "C4",
          topic: "Bab 4 · Lukisan Berskala (KBAT)",
          isKbat: true,
          context: "Pelan sebuah bilik berskala 1:50 menunjukkan segi empat tepat 10 cm × 6 cm.",
          parts: [
            { label: "(a)", prompt: "Cari panjang sebenar bilik itu (m).", answer: "5", marks: 3 },
            { label: "(b)", prompt: "Cari lebar sebenar bilik itu (m).", answer: "3", marks: 4 },
            { label: "(c)", prompt: "Cari luas sebenar bilik itu (m²).", answer: "15", marks: 3 },
          ],
          solution: [
            "Panjang sebenar = 10 × 50 = 500 cm = 5 m",
            "Lebar sebenar = 6 × 50 = 300 cm = 3 m",
            "Luas = 5 × 3 = 15 m²",
          ],
        },
        {
          id: "C5",
          topic: "Bab 5 · Nisbah Trigonometri (KBAT)",
          isKbat: true,
          context: "Sebuah papan gelongsor panjang 6 m disandarkan daripada platform ke tanah, membentuk sudut 45° dengan tanah. (Gunakan sin 45° ≈ 0.71, kos 45° ≈ 0.71)",
          parts: [
            { label: "(a)", prompt: "Cari tinggi platform (m).", answer: "4.26", marks: 4 },
            { label: "(b)", prompt: "Cari jarak mendatar daripada kaki papan ke platform (m).", answer: "4.26", marks: 3 },
            { label: "(c)", prompt: "Jika papan diperpanjang kepada 10 m dengan sudut yang sama, cari tinggi platform baharu (m).", answer: "7.1", marks: 3 },
          ],
          solution: [
            "Tinggi = 6 × sin 45° = 6 × 0.71 = 4.26 m",
            "Jarak mendatar = 6 × kos 45° = 6 × 0.71 = 4.26 m",
            "Tinggi baharu = 10 × sin 45° = 10 × 0.71 = 7.1 m",
          ],
        },
        {
          id: "C6",
          topic: "Bab 1 dan 3 · Indeks & Matematik Pengguna (KBAT)",
          isKbat: true,
          context: "Sebuah pelaburan bermula RM900 dan berganda mengikut faktor 3 setiap 2 tahun (nilai = 900 × 3ⁿ, dengan n = bilangan kitaran 2 tahun).",
          parts: [
            { label: "(a)", prompt: "Cari nilai pelaburan (RM) selepas 4 tahun (n = 2).", answer: "8100", marks: 4 },
            { label: "(b)", prompt: "Selepas berapa TAHUN nilai pelaburan mencapai RM24300?", answer: "6", marks: 3 },
            { label: "(c)", prompt: "Selepas 10 tahun, faktor pendaraban ialah 3ᵏ. Apakah nilai k?", answer: "5", marks: 3 },
          ],
          solution: [
            "Selepas 4 tahun, n = 2: nilai = 900 × 3² = 900 × 9 = RM8100",
            "RM24300 = 900 × 3ⁿ → 3ⁿ = 27 = 3³ → n = 3 → tahun = 3 × 2 = 6 tahun",
            "Selepas 10 tahun, n = 10 ÷ 2 = 5, jadi k = 5",
          ],
        },
      ],
    },
  ],
};
